# Generated by Django 3.1.3 on 2021-12-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, max_length=10, null=True, verbose_name='Начало')),
                ('date_of_end', models.DateField(blank=True, max_length=10, null=True, verbose_name='Окончание')),
                ('type_of_act', models.CharField(blank=True, max_length=150, null=True, verbose_name='тип акта преследования')),
                ('сase_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='номер дела в суде')),
                ('сase_decision', models.CharField(blank=True, max_length=50, null=True, verbose_name='тип судебного решения')),
                ('sentence', models.CharField(blank=True, max_length=50, null=True, verbose_name='тип приговора')),
                ('year_sentence', models.CharField(blank=True, max_length=2, null=True, verbose_name='лет')),
                ('month_sentence', models.CharField(blank=True, max_length=2, null=True, verbose_name='месяцев')),
                ('day_sentence', models.CharField(blank=True, max_length=4, null=True, verbose_name='дней')),
                ('penalty_sentence', models.CharField(blank=True, max_length=15, null=True, verbose_name='штраф')),
                ('work_sentence', models.CharField(blank=True, max_length=4, null=True, verbose_name='принудительные работы')),
                ('text_sentence', models.TextField(blank=True, null=True, verbose_name='текст приговора')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('appeal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitedb.act')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='статья')),
                ('parts', models.CharField(blank=True, max_length=20, null=True, verbose_name='часть')),
                ('code', models.CharField(choices=[('УК', 'Уголовный кодекс'), ('КоАП', 'Кодекс об административных правонарушениях')], default='УК', max_length=10, verbose_name='кодекс')),
                ('title', models.TextField(blank=True, null=True, verbose_name='название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Дело')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default='images/Noface.JPG', null=True, upload_to='static/images/cases')),
            ],
        ),
        migrations.CreateModel(
            name='H_Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(max_length=150, unique=True, verbose_name='Права свободы')),
                ('echr_article', models.CharField(blank=True, max_length=15, null=True, verbose_name='статья')),
                ('content', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=250, verbose_name='короткое название')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='полное название')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='адрес')),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон')),
                ('site_org', models.URLField(blank=True, max_length=250, null=True, verbose_name='сайт')),
                ('Email', models.URLField(blank=True, max_length=250, null=True, verbose_name='E-mail')),
                ('prison', models.BooleanField(blank=True, default=False, null=True, verbose_name='место лишения свободы')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='страна расположения')),
                ('main_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitedb.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Persecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pers', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип преследования')),
                ('date', models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата преследования')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitedb.case')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='биография')),
                ('photo', models.ImageField(default='images/Noface.JPG', null=True, upload_to='sitedb/images/person')),
                ('citizenship', models.CharField(blank=True, max_length=250, null=True, verbose_name='гражданство')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='короткое название')),
                ('overwrite', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationInAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.act')),
                ('rights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.h_rights')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOfVictimInPers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Підозрюваний', max_length=100, verbose_name='статус')),
                ('date', models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата начала статуса')),
                ('date_of_end', models.DateField(blank=True, max_length=10, null=True, verbose_name='Окончание статуса')),
                ('persecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.persecution')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='должность')),
                ('rank', models.CharField(blank=True, max_length=250, null=True, verbose_name='звание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='начало работы')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='прекращение работы')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='пометки')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.person')),
                ('оrganisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitedb.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonInAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_in_act', models.CharField(default='Винний', max_length=250, verbose_name='статус в акте')),
                ('role', models.CharField(blank=True, max_length=250, null=True, verbose_name='роль в акте')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.act')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.person')),
            ],
        ),
        migrations.AddField(
            model_name='persecution',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.person'),
        ),
        migrations.CreateModel(
            name='OrganisationInAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.act')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='srtucture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitedb.structure'),
        ),
        migrations.CreateModel(
            name='Depriving_Liberty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, verbose_name='Начало')),
                ('date_of_end', models.DateField(blank=True, max_length=10, null=True, verbose_name='Окончание')),
                ('condition', models.CharField(blank=True, max_length=250, null=True, verbose_name='Умови')),
                ('status', models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.organisation')),
                ('persecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.persecution')),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesInPersecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.article')),
                ('persecution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.persecution')),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='persecution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitedb.persecution'),
        ),
    ]
