# Generated by Django 3.1.3 on 2021-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedb', '0002_persecution_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='logo',
            field=models.ImageField(default='images/Nologo.JPG', null=True, upload_to='sitedb/images/structure'),
        ),
    ]
